version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/qivr-api
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - docker buildx create --name multi --use 2>/dev/null || docker buildx use multi
      - docker buildx inspect --bootstrap

  build:
    commands:
      - echo Build started on `date`

      # Start Docker build in background (takes longest)
      - echo Building Docker image...
      - docker buildx build --platform linux/amd64 -t $REPOSITORY_URI:$IMAGE_TAG -t $REPOSITORY_URI:latest --push ./backend &
      - DOCKER_PID=$!

      # While Docker builds, install npm deps and build frontends in parallel
      - echo Installing Node.js dependencies...
      - npm ci --legacy-peer-deps 2>/dev/null || npm install --legacy-peer-deps

      - echo Building packages and frontends...
      - npm run build:packages --if-present || (cd packages/http && npm run build && cd ../.. && cd packages/design-system && npm run build && cd ../..)
      
      # Build frontends in parallel
      - cd apps/clinic-dashboard && npm run build &
      - CLINIC_PID=$!
      - cd apps/patient-portal && npm run build &
      - PATIENT_PID=$!
      
      # Wait for frontend builds
      - wait $CLINIC_PID
      - wait $PATIENT_PID
      
      # Wait for Docker build to complete
      - echo Waiting for Docker build...
      - wait $DOCKER_PID

      # Run database migrations using .NET 10 Docker image
      - echo Running database migrations...
      - |
        DB_SECRET=$(aws secretsmanager get-secret-value --secret-id qivr/production/database --query SecretString --output text)
        DB_HOST=$(echo $DB_SECRET | jq -r '.host')
        DB_USER=$(echo $DB_SECRET | jq -r '.username')
        DB_PASS=$(echo $DB_SECRET | jq -r '.password')
        DB_NAME=$(echo $DB_SECRET | jq -r '.database')
        docker run --rm --platform linux/amd64 \
          -e "ConnectionStrings__DefaultConnection=Host=$DB_HOST;Database=$DB_NAME;Username=$DB_USER;Password=$DB_PASS" \
          -v $(pwd)/backend:/app \
          -w /app \
          mcr.microsoft.com/dotnet/sdk:10.0-preview-alpine \
          sh -c "dotnet tool restore && dotnet ef database update --project Qivr.Infrastructure --startup-project Qivr.Api" \
          || echo "Migration completed or no pending migrations"

  post_build:
    commands:
      - echo Build completed on `date`

      # Deploy frontends to S3 in parallel
      - aws s3 sync apps/clinic-dashboard/dist/ s3://qivr-clinic-dashboard-production --delete --region $AWS_DEFAULT_REGION &
      - aws s3 sync apps/patient-portal/dist/ s3://qivr-patient-portal-production --delete --region $AWS_DEFAULT_REGION &
      - wait

      # Invalidate CloudFront caches in parallel
      - aws cloudfront create-invalidation --distribution-id E1S9SAZB57T3C3 --paths "/*" &
      - aws cloudfront create-invalidation --distribution-id E39OVJDZIZ22QL --paths "/*" &

      # Update ECS service
      - sed "s|IMAGE_URI_PLACEHOLDER|$REPOSITORY_URI:$IMAGE_TAG|g" task-definition-template.json > task-definition-new.json
      - NEW_TASK_DEF=$(aws ecs register-task-definition --cli-input-json file://task-definition-new.json --query 'taskDefinition.taskDefinitionArn' --output text)
      - aws ecs update-service --cluster qivr_cluster --service qivr-api --task-definition $NEW_TASK_DEF --force-new-deployment
      - printf '[{"name":"qivr-api","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - wait

artifacts:
  files:
    - imagedefinitions.json
