version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      dotnet: 8.0

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/qivr-api
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      # Enable Buildx for multi-arch builds
      - echo Enabling Docker Buildx...
      - docker buildx version || true
      - docker buildx create --name multi --use || docker buildx use multi
      - docker buildx inspect --bootstrap

  build:
    commands:
      - echo Build started on `date`

      # Build and push multi-arch backend image
      - echo Building multi-arch Docker image and pushing to ECR...
      - docker buildx build --platform linux/amd64 -t $REPOSITORY_URI:$IMAGE_TAG -t $REPOSITORY_URI:latest --push ./backend

      # Run database migrations
      - echo Running database migrations...
      - |
        DB_SECRET=$(aws secretsmanager get-secret-value --secret-id qivr/production/database --query SecretString --output text)
        DB_HOST=$(echo $DB_SECRET | jq -r '.host')
        DB_USER=$(echo $DB_SECRET | jq -r '.username')
        DB_PASS=$(echo $DB_SECRET | jq -r '.password')
        DB_NAME=$(echo $DB_SECRET | jq -r '.database')
        export ConnectionStrings__DefaultConnection="Host=$DB_HOST;Database=$DB_NAME;Username=$DB_USER;Password=$DB_PASS"
        cd backend/Qivr.Api
        dotnet tool restore || dotnet tool install --global dotnet-ef
        dotnet ef database update --project ../Qivr.Infrastructure --startup-project . --verbose || echo "Migration completed or no pending migrations"
        cd ../..

      # Build frontends
      - echo Installing Node.js dependencies...
      - rm -f package-lock.json
      - npm install --legacy-peer-deps

      - echo Building http package...
      - cd packages/http
      - npm run build
      - cd ../..

      - echo Building design system...
      - cd packages/design-system
      - npm run build
      - cd ../..

      - echo Building clinic dashboard...
      - cd apps/clinic-dashboard
      - npm run build
      - cd ../..

      - echo Building patient portal...
      - cd apps/patient-portal
      - npm run build
      - cd ../..

  post_build:
    commands:
      - echo Build completed on `date`

      # Deploy frontends to S3
      - echo Deploying clinic dashboard to S3...
      - aws s3 sync apps/clinic-dashboard/dist/ s3://qivr-clinic-dashboard-production --delete --region $AWS_DEFAULT_REGION

      - echo Deploying patient portal to S3...
      - aws s3 sync apps/patient-portal/dist/ s3://qivr-patient-portal-production --delete --region $AWS_DEFAULT_REGION

      - echo Invalidating CloudFront caches...
      - aws cloudfront create-invalidation --distribution-id E1S9SAZB57T3C3 --paths "/*"
      - aws cloudfront create-invalidation --distribution-id E39OVJDZIZ22QL --paths "/*"

      # Create new task definition
      - echo Creating new task definition...
      - sed "s|IMAGE_URI_PLACEHOLDER|$REPOSITORY_URI:$IMAGE_TAG|g" task-definition-template.json > task-definition-new.json

      # Register new task definition
      - echo Registering new task definition...
      - NEW_TASK_DEF=$(aws ecs register-task-definition --cli-input-json file://task-definition-new.json --query 'taskDefinition.taskDefinitionArn' --output text)
      - echo "New task definition:" $NEW_TASK_DEF

      # Update service with new task definition
      - echo Updating ECS service...
      - aws ecs update-service --cluster qivr_cluster --service qivr-api --task-definition $NEW_TASK_DEF --force-new-deployment

      - echo Writing image definitions file...
      - printf '[{"name":"qivr-api","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
