version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/qivr-api
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Build started on `date`
      
      # Build backend Docker image
      - echo Building the Docker image...
      - cd backend
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - cd ..
      
      # Build frontend apps
      - echo Building frontend applications...
      - cd packages/http
      - npm ci
      - npm run build
      - cd ../../apps/clinic-dashboard
      - npm ci
      - npm run build
      - cd ../patient-portal
      - npm ci
      - npm run build
      - cd ../..

  post_build:
    commands:
      - echo Build completed on `date`
      
      # Push backend image
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      
      # Deploy frontend to S3
      - echo Deploying frontend applications...
      - aws s3 sync apps/clinic-dashboard/dist/ s3://qivr-clinic-dashboard-staging --delete
      - aws s3 sync apps/patient-portal/dist/ s3://qivr-patient-portal-staging --delete
      
      # Invalidate CloudFront
      - aws cloudfront create-invalidation --distribution-id E1S9SAZB57T3C3 --paths "/*"
      - aws cloudfront create-invalidation --distribution-id E39OVJDZIZ22QL --paths "/*"
      
      # Force ECS deployment
      - echo Forcing ECS service deployment...
      - aws ecs update-service --cluster qivr_cluster --service qivr-api --force-new-deployment
      
      - echo Writing image definitions file...
      - printf '[{"name":"qivr-api","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
