version: 0.2

env:
  variables:
    FORCE_BUILD_ALL: "false"

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/qivr-api
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

      # Detect what changed since last successful build
      - |
        echo "Detecting changes..."
        PREV_COMMIT=$(aws ssm get-parameter --name /qivr/last-successful-build --query Parameter.Value --output text 2>/dev/null || echo "")
        if [ -z "$PREV_COMMIT" ] || [ "$FORCE_BUILD_ALL" = "true" ]; then
          echo "No previous build found or force build - building all"
          BUILD_BACKEND=true
          BUILD_CLINIC=true
          BUILD_PATIENT=true
          BUILD_ADMIN=false
          BUILD_PARTNER=false
          BUILD_WIDGET=true
        else
          echo "Comparing $PREV_COMMIT to $CODEBUILD_RESOLVED_SOURCE_VERSION"
          git fetch --depth=100 origin main 2>/dev/null || true
          CHANGED_FILES=$(git diff --name-only $PREV_COMMIT $CODEBUILD_RESOLVED_SOURCE_VERSION 2>/dev/null || echo "")
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changes detected or git diff failed - building all to be safe"
            BUILD_BACKEND=true; BUILD_CLINIC=true; BUILD_PATIENT=true; BUILD_ADMIN=false; BUILD_PARTNER=false; BUILD_WIDGET=true
          else
            BUILD_BACKEND=$(echo "$CHANGED_FILES" | grep -q "^backend/\|^packages/" && echo true || echo false)
            BUILD_CLINIC=$(echo "$CHANGED_FILES" | grep -q "^apps/clinic-dashboard/\|^packages/" && echo true || echo false)
            BUILD_PATIENT=$(echo "$CHANGED_FILES" | grep -q "^apps/patient-portal/\|^packages/" && echo true || echo false)
            BUILD_ADMIN=false
            BUILD_PARTNER=false
            BUILD_WIDGET=$(echo "$CHANGED_FILES" | grep -q "^apps/intake-widget/\|^packages/" && echo true || echo false)
          fi
        fi
        echo "BUILD_BACKEND=$BUILD_BACKEND BUILD_CLINIC=$BUILD_CLINIC BUILD_PATIENT=$BUILD_PATIENT BUILD_ADMIN=$BUILD_ADMIN BUILD_PARTNER=$BUILD_PARTNER BUILD_WIDGET=$BUILD_WIDGET"

      - docker buildx create --name multi --use 2>/dev/null || docker buildx use multi
      - docker buildx inspect --bootstrap

  build:
    commands:
      - echo Build started on `date`

      # Build Docker image synchronously if backend changed (must complete before post_build)
      - |
        if [ "$BUILD_BACKEND" = "true" ]; then
          echo "Building and pushing Docker image..."
          docker buildx build --platform linux/amd64 -t $REPOSITORY_URI:$IMAGE_TAG -t $REPOSITORY_URI:latest --push ./backend
          echo "Docker build and push completed"
        else
          echo "Skipping backend build - no changes"
        fi

      # Only install deps if any frontend needs building
      - |
        if [ "$BUILD_CLINIC" = "true" ] || [ "$BUILD_PATIENT" = "true" ] || [ "$BUILD_ADMIN" = "true" ] || [ "$BUILD_PARTNER" = "true" ] || [ "$BUILD_WIDGET" = "true" ]; then
          echo "Installing Node.js dependencies..."
          npm ci --legacy-peer-deps 2>/dev/null || npm install --legacy-peer-deps
          echo "Building shared packages..."
          cd packages/http && npm run build && cd ../..
          cd packages/eval && npm run build && cd ../..
          cd packages/design-system && npm run build && cd ../..
        fi

      # Build only changed frontends in parallel
      - |
        PIDS=""
        if [ "$BUILD_CLINIC" = "true" ]; then
          echo "Building clinic-dashboard..."
          (cd apps/clinic-dashboard && npm run build) &
          PIDS="$PIDS $!"
        fi
        if [ "$BUILD_PATIENT" = "true" ]; then
          echo "Building patient-portal..."
          (cd apps/patient-portal && npm run build) &
          PIDS="$PIDS $!"
        fi
        if [ "$BUILD_ADMIN" = "true" ]; then
          echo "Building admin-portal..."
          (cd apps/admin-portal && npm run build) &
          PIDS="$PIDS $!"
        fi
        if [ "$BUILD_PARTNER" = "true" ]; then
          echo "Building partner-portal..."
          (cd apps/partner-portal && npm run build) &
          PIDS="$PIDS $!"
        fi
        if [ "$BUILD_WIDGET" = "true" ]; then
          echo "Building intake-widget..."
          (cd apps/intake-widget && npm run build) &
          PIDS="$PIDS $!"
        fi
        for pid in $PIDS; do wait $pid; done

      # Migrations are managed manually via SQL - not run in CI/CD

  post_build:
    commands:
      - echo Build completed on `date`

      # Deploy only changed frontends (sequential to ensure completion)
      - |
        if [ "$BUILD_CLINIC" = "true" ]; then
          echo "Deploying clinic-dashboard..."
          aws s3 sync apps/clinic-dashboard/dist/ s3://qivr-clinic-dashboard-production --delete --region $AWS_DEFAULT_REGION
        fi
        if [ "$BUILD_PATIENT" = "true" ]; then
          echo "Deploying patient-portal..."
          aws s3 sync apps/patient-portal/dist/ s3://qivr-patient-portal-production --delete --region $AWS_DEFAULT_REGION
        fi
        if [ "$BUILD_ADMIN" = "true" ]; then
          echo "Deploying admin-portal..."
          aws s3 sync apps/admin-portal/dist/ s3://qivr-admin-portal --delete --region $AWS_DEFAULT_REGION
        fi
        if [ "$BUILD_PARTNER" = "true" ]; then
          echo "Deploying partner-portal..."
          aws s3 sync apps/partner-portal/dist/ s3://qivr-partner-portal --delete --region $AWS_DEFAULT_REGION
        fi
        if [ "$BUILD_WIDGET" = "true" ]; then
          echo "Deploying intake-widget..."
          aws s3 sync apps/intake-widget/dist/ s3://qivr-intake-widget --delete --region $AWS_DEFAULT_REGION
        fi

      # Invalidate only changed CloudFront distributions (sequential to ensure completion)
      - |
        if [ "$BUILD_CLINIC" = "true" ]; then
          echo "Invalidating clinic CloudFront..."
          aws cloudfront create-invalidation --distribution-id E1S9SAZB57T3C3 --paths "/*"
        fi
        if [ "$BUILD_PATIENT" = "true" ]; then
          echo "Invalidating patient CloudFront..."
          aws cloudfront create-invalidation --distribution-id E39OVJDZIZ22QL --paths "/*"
        fi
        if [ "$BUILD_ADMIN" = "true" ]; then
          echo "Invalidating admin CloudFront..."
          aws cloudfront create-invalidation --distribution-id E30RX4A147QBCE --paths "/*"
        fi
        if [ "$BUILD_PARTNER" = "true" ]; then
          echo "Invalidating partner CloudFront..."
          aws cloudfront create-invalidation --distribution-id E3TORP1KMGHC6H --paths "/*"
        fi

      # Update ECS service only if backend changed
      - |
        if [ "$BUILD_BACKEND" = "true" ]; then
          echo "Updating ECS service..."
          sed "s|IMAGE_URI_PLACEHOLDER|$REPOSITORY_URI:$IMAGE_TAG|g" task-definition-template.json > task-definition-new.json
          NEW_TASK_DEF=$(aws ecs register-task-definition --cli-input-json file://task-definition-new.json --query 'taskDefinition.taskDefinitionArn' --output text)
          aws ecs update-service --cluster qivr_cluster --service qivr-api --task-definition $NEW_TASK_DEF --force-new-deployment
          printf '[{"name":"qivr-api","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
        else
          echo '[]' > imagedefinitions.json
        fi
        wait

      # Store successful build commit for next comparison
      - aws ssm put-parameter --name /qivr/last-successful-build --value $CODEBUILD_RESOLVED_SOURCE_VERSION --type String --overwrite

artifacts:
  files:
    - imagedefinitions.json
