-- Add new columns to medical_devices table
ALTER TABLE medical_devices ADD COLUMN IF NOT EXISTS technical_specifications TEXT;
ALTER TABLE medical_devices ADD COLUMN IF NOT EXISTS global_availability TEXT;

-- Insert Medtronic as a research partner if not exists
INSERT INTO research_partners (id, name, slug, contact_email, description, website, is_active, created_at, updated_at)
VALUES ('11111111-1111-1111-1111-111111111111', 'Medtronic', 'medtronic', 'partners@medtronic.com', 'Global leader in medical technology, services, and solutions', 'https://www.medtronic.com', true, NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- Insert Medtronic orthopedic devices
INSERT INTO medical_devices (id, partner_id, name, device_code, category, body_region, description, technical_specifications, global_availability, is_active, created_at, updated_at) VALUES
('d0000001-0001-0001-0001-000000000001', '11111111-1111-1111-1111-111111111111', 'Kyphon Balloon Kyphoplasty Platform', 'KYP-BKP-001', 'Vertebral Augmentation', 'Spine', 'Orthopedic balloon system used to treat vertebral compression fractures by restoring vertebral height and stabilizing fractures.', 'Inflatable bone tamps (IBTs) rated up to 700 psi inflation pressure; cement delivery system allows injection of high-viscosity PMMA cement from a safe distance (~48 inches) while maintaining fracture reduction.', 'FDA-cleared and CE-marked; available worldwide (used in North America, Europe, Asia-Pacific) for minimally invasive spine fracture repair.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000002', '11111111-1111-1111-1111-111111111111', 'Kyphon V Vertebroplasty Platform', 'KYP-VRT-001', 'Vertebral Augmentation', 'Spine', 'Premium vertebroplasty system for precise delivery of bone cement to vertebral compression fractures.', 'Utilizes high-viscosity radiopaque PMMA bone cement (e.g., Kyphon HV-R or VuE) for controlled vertebral body filling; compatible with unipedicular or bipedicular access and directional cannulas for targeted cement placement.', 'Cleared in major markets (U.S. FDA, Europe CE) as a minimally invasive treatment for osteoporotic or metastatic vertebral body fractures; marketed globally alongside kyphoplasty products.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000003', '11111111-1111-1111-1111-111111111111', 'Infuse Bone Graft', 'INF-BMP-001', 'Bone Graft', 'Spine', 'Recombinant human Bone Morphogenetic Protein-2 (rhBMP-2) on an absorbable collagen sponge that induces new bone formation; an alternative to autograft for spine fusion and specific orthopedic trauma.', 'Supplied as a kit (rhBMP-2 powder to be reconstituted – 1.5 mg/mL solution – and collagen sponges) placed inside Medtronic interbody cages; stimulates bone growth over 6–12 months, replacing the sponge with mature bone. Approved indications include single-level ALIF (with LT-Cage), acute open tibial fractures, and certain oral/maxillofacial uses.', 'Widely available: FDA-approved for limited uses in the USA (e.g. spine, tibia) and CE-marked in Europe (broader dental and orthopedic indications); used globally in spine fusion surgeries.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000004', '11111111-1111-1111-1111-111111111111', 'Grafton Demineralized Bone Matrix (DBM)', 'GRF-DBM-001', 'Bone Graft', 'Spine', 'Allograft bone graft extender and bone void filler made from processed human bone; one of the most studied DBM products with consistently high osteoinductivity.', 'Provided in multiple forms (putty, gel, paste, chips) with proprietary processing that preserves native growth factors and a fiber-based scaffold for osteoconduction. Each lot is tested for inductive potential; used alone or mixed with autograft to enhance fusion.', 'Globally available tissue allograft (regulated as HCT/P in US and CE-marked in EU); in clinical use across North America, Europe, Japan, and other regions for spinal, orthopedic, and dental bone grafting procedures.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000005', '11111111-1111-1111-1111-111111111111', 'MasterGraft Synthetic Bone Graft', 'MGR-SYN-001', 'Bone Graft', 'Spine', 'Family of synthetic osteoconductive, resorbable scaffolds for bone regeneration; used as bone graft substitutes or extenders in spine and trauma surgeries.', 'Comprised of medical-grade calcium phosphate ceramics (85% β-TCP/15% HA) often combined with type I collagen. Available in granules, strips, and putty forms that mimic cancellous bone structure (porous matrix for cell ingrowth). Completely resorbs over time and is replaced by native bone during healing.', 'Marketed globally (FDA 510(k)-cleared and CE-marked) as a scaffold for orthopedic and dental applications. Used in the U.S., EU, Asia, and other regions in conjunction with autograft or biologics to promote spinal fusion and bone defect healing.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000006', '11111111-1111-1111-1111-111111111111', 'Magnifuse Bone Graft (DBM)', 'MAG-DBM-001', 'Bone Graft', 'Spine', 'Demineralized bone matrix product consisting of sterile allograft bone fibers used to fill bony voids or gaps in the skeletal system.', 'Provided as a moldable graft material with a mesh carrier (Magnifuse I includes a bioresorbable PGA mesh) to contain the demineralized fibers at the implantation site. Can be mixed with fluid (blood or bone marrow aspirate) to improve handling. The DBM fibers provide osteoconductive scaffold and osteoinductive potential.', 'Cleared for use in the United States (FDA) for posterolateral spine fusion and orthopedic applications; also distributed in select international markets.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000007', '11111111-1111-1111-1111-111111111111', 'CD Horizon Solera Spinal System', 'CDH-SOL-001', 'Spinal Fixation', 'Thoracolumbar', 'Comprehensive posterior thoracolumbar fixation system for spinal stabilization from T1 to pelvis. Uses pedicle screws and rods to correct deformity and stabilize the spine in fusion procedures.', 'Supports 5.5 mm and 6.0 mm diameter rods (titanium or cobalt-chrome) for construct rigidity tailoring. Features various screw types: multi-axial screws, reduction screws, and dual-rod connectors. Compatible with minimally invasive percutaneous tools (Solera Voyager) and cement-augmented fenestrated screws for tumor or osteoporotic cases.', 'Widely used globally: FDA-approved in the U.S. and CE-marked in Europe for spinal fusion. Standard of care in many regions for degenerative spine, deformity (scoliosis, kyphosis), and trauma.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000008', '11111111-1111-1111-1111-111111111111', 'Infinity OCT Spine System', 'INF-OCT-001', 'Spinal Fixation', 'Cervical', 'Occipito-cervical-thoracic fixation system designed to stabilize the upper spine (occiput through T3) in complex cervical cases.', 'Includes multi-axial screws for C1–C7 and hooks/rod connectors for occiput and upper thoracic levels. Features modular plates and rods plus the ability to integrate patient-specific UNiD rods (pre-bent to match alignment goals). Connects seamlessly to thoracolumbar rod systems for long constructs.', 'Introduced globally (FDA cleared, CE marked circa 2017) and adopted in North America, Europe, Asia for posterior cervical fusion in cases of instability (trauma, tumors), deformity, or failed previous fusions.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000009', '11111111-1111-1111-1111-111111111111', 'Prestige LP Cervical Disc', 'PRS-LP-001', 'Artificial Disc', 'Cervical', 'Second-generation Prestige LP artificial cervical disc for motion preservation at one or two adjacent levels in the neck.', 'Low-profile two-piece metal-on-metal design made of titanium-ceramic composite. Incorporates a ball-and-trough articulation that permits physiological range of motion. Compared to the earlier stainless-steel Prestige ST, the LP has a slimmer profile and is MRI-safe. Implanted using an anterior approach to replace a diseased disc (C3–C7).', 'Approved and marketed internationally: gained FDA approval (for 1- and 2-level use) and CE mark in Europe. Available in the U.S., Canada, Europe, Australia, and Asia.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000010', '11111111-1111-1111-1111-111111111111', 'Bryan Cervical Disc', 'BRY-CD-001', 'Artificial Disc', 'Cervical', 'A viscoelastic cervical disc prosthesis that preserves motion with an elastic nucleus design. It was one of the first cervical discs with a polymer core.', 'Composed of two titanium alloy shells and a polyurethane polymer core enclosed by a flexible membrane. The design allows shock absorption and a controlled range of motion. The device has no rigid ball-in-socket interface; the deformable core permits multi-directional movement.', 'Widely implanted in Europe since early 2000s and FDA approved in 2009. Used in North America, Europe, Asia and other regions for single-level cervical disc replacement.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000011', '11111111-1111-1111-1111-111111111111', 'SynchroMed II/III Intrathecal Pump', 'SYN-ITP-001', 'Drug Delivery', 'Spine', 'Fully implantable, programmable drug infusion pump for chronic pain and severe spasticity management. Delivers medication (e.g., morphine, baclofen) directly into the intrathecal space.', 'Titanium pump available in 20 mL or 40 mL reservoir sizes. Uses a battery-powered peristaltic mechanism with diamond-like carbon coated gears for durability. Delivers medication at precise programmable rates with ±0.3% repeatability in flow. Designed to last up to seven years. MRI SureScan conditional for 1.5/3T scans.', 'Global reach: thousands of implants worldwide. FDA-approved in US and widely available in Europe, Canada, Australia, etc., with over 30 years of clinical use.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000012', '11111111-1111-1111-1111-111111111111', 'Intellis Spinal Cord Stimulator', 'INT-SCS-001', 'Neuromodulation', 'Spine', 'Rechargeable spinal cord stimulation system for chronic intractable pain. Intellis is noted as the world''s smallest fully implantable SCS neurostimulator.', 'Contains a 16-contact implantable pulse generator that delivers customizable electrical pulses to the spinal cord. Features the Evolve workflow and AdaptiveStim technology for optimizing therapy; can record and track patient activity 24/7 via onboard sensors. Full-body MRI conditional with SureScan technology.', 'Commercially launched in 2017 after FDA and CE approvals. Deployed in pain clinics and hospitals across North America, Europe, Australia, and Asia.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000013', '11111111-1111-1111-1111-111111111111', 'Vanta SCS (Recharge-free Neurostimulator)', 'VNT-SCS-001', 'Neuromodulation', 'Spine', 'Implantable spinal cord stimulator for chronic pain that does not require recharging. Emphasizes long battery life and efficient pain relief.', 'Non-rechargeable battery designed to last up to ~11 years (depending on settings), roughly double the longevity of previous non-rechargeable models. Provides both tonic and burst stimulation modes, including compatibility with Medtronic''s DTM waveform therapy.', 'Approved by FDA in 2021 and launched in US and Europe as a competitor in the recharge-free SCS market. Available in many countries in Europe and Asia-Pacific.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000014', '11111111-1111-1111-1111-111111111111', 'Aquamantys Bipolar Sealer', 'AQM-BPS-001', 'Surgical Energy', 'General', 'Advanced electrosurgical device that provides hemostatic sealing of soft tissue and bone using radiofrequency (RF) energy combined with saline irrigation.', 'Utilizes Transcollation technology, where RF energy at ~100 kHz heats tissue while continuous saline flow cools the tissue, preventing charring. This achieves a seal of blood vessels (up to ~1 mm) with minimal thermal damage. No smoke or carbonization is produced.', 'Available globally (originally developed by Salient Surgical, acquired by Medtronic). Used in hospitals across the US, EU, Asia for spine surgery, hip/knee arthroplasty, trauma, and tumor resections.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000015', '11111111-1111-1111-1111-111111111111', 'PEAK PlasmaBlade System', 'PEK-PLB-001', 'Surgical Energy', 'General', 'Low-thermal electrosurgical cutting device offering scalpel-like precision with minimal collateral tissue damage.', 'Employs pulsed plasma-mediated RF energy to dissect tissue at lower temperatures than conventional continuous-wave cautery. Handheld disposable PlasmaBlade devices connect to a control console that modulates short high-voltage pulses to create an ionized plasma along the blade edge.', 'Introduced by Medtronic (via acquisition of PEAK Surgical) and cleared by FDA for general surgery. Widely adopted in specialties like plastic/reconstructive surgery, ENT, orthopedics, and neurosurgery. CE marked.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000016', '11111111-1111-1111-1111-111111111111', 'Midas Rex MR8 High-Speed Drill', 'MRX-MR8-001', 'Powered Instruments', 'Spine/Cranial', 'High-torque surgical drill system for cutting bone in spine, cranial, and other orthopedic surgeries. Renowned for its power and precision in bone drilling and dissection.', 'Operates at speeds up to ~75,000 RPM with consistent torque. Available in pneumatic or electric versions. Features a lightweight, ergonomically balanced handpiece for reduced fatigue. Accepts a wide range of attachments and dissecting burs. Can be integrated with StealthStation for navigated drilling.', 'Longstanding global presence – a gold standard in neurosurgical drills for decades. Used in operating rooms worldwide (FDA cleared and CE marked).', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000017', '11111111-1111-1111-1111-111111111111', 'Spine Shaver Nucleus Removal Set', 'SPS-NRS-001', 'Powered Instruments', 'Spine', 'Minimally invasive disc nucleus removal tool designed to evacuate intervertebral disc material through a small cannula.', 'Consists of an oscillating aspiration cutter that attaches to the Midas Rex drill console. The disposable shaver blade oscillates at ~5,000 cycles per minute, macerating nucleus pulposus tissue, which is simultaneously suctioned out. Integrated irrigation helps keep the disc space clear.', 'Offered internationally as part of Medtronic''s minimally invasive spine surgery portfolio. Cleared by FDA and carrying CE marking.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000018', '11111111-1111-1111-1111-111111111111', 'Midas Rex Bone Mill', 'MRX-BML-001', 'Powered Instruments', 'Spine', 'Electric bone mill system for morselizing bone graft into optimal particle sizes for fusion or repair.', 'Designed to process autograft or allograft bone into uniform chips. Typically interfaces with a Midas Rex power source. Provides a quick, controlled way to create bone graft material compared to manual rongeurs.', 'Distributed globally alongside Medtronic''s spinal hardware and biologics. Approved for use in North America, EU and other regions as a Class I medical device.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000019', '11111111-1111-1111-1111-111111111111', 'Powerease System', 'PWR-EAS-001', 'Powered Instruments', 'Spine', 'Battery-powered instrument set to assist surgeons in driving screws and cutting rods during spinal instrumentation procedures, reducing manual effort.', 'Includes a sterile-pack power drill/driver handpiece with attachments for Medtronic screws, taps, and drill bits. Also features a power rod cutter and set-screw breaker. Provides consistent speed and torque, potentially improving OR efficiency.', 'Initially launched in the US (FDA cleared) and Europe, it''s offered wherever Medtronic spinal systems are sold. Supports all CD Horizon rod diameters (4.75 mm to 6.35 mm).', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000020', '11111111-1111-1111-1111-111111111111', 'Mazor X Stealth Edition Robot', 'MZR-XSE-001', 'Robotic Surgery', 'Spine', 'Robotic surgical guidance system for spine procedures, integrating Mazor robotic arm technology with StealthStation navigation for precise implant placement.', 'Enables preoperative planning of screw trajectories and automated alignment of a robotic arm to guide instruments along planned paths. The system mounts to the OR table and uses a small rigid arm to position drill guides. Stealth Edition integrates real-time navigation feedback.', 'FDA cleared and CE marked (introduced after Medtronic''s 2018 acquisition of Mazor Robotics). In use at leading spine centers in the Americas, Europe, Australia, and parts of Asia.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000021', '11111111-1111-1111-1111-111111111111', 'O-arm Surgical Imaging System', 'OAR-IMG-001', 'Imaging', 'Spine', 'Mobile intraoperative imaging device providing 2D fluoroscopy and 3D CT-quality scans on demand during surgery. Commonly used for spinal and orthopedic procedures.', 'Features a circular O-shaped gantry that encloses the patient; performs 360° rotation in 3D scan mode. Delivers multi-plane 2D images or a 3D volumetric dataset (15–30 cm field) in under 30 seconds. The latest O-arm O2 supports 3D image fusion with StealthStation navigation.', 'Extensive global adoption since mid-2000s: FDA cleared and CE marked. Installed in hospitals across North/South America, Europe, Asia, and the Middle East.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000022', '11111111-1111-1111-1111-111111111111', 'StealthStation S8 Navigation', 'STL-S8-001', 'Navigation', 'Spine/Cranial', 'Computer-assisted surgery system that enables real-time tracking of surgical instruments relative to patient anatomy during neurosurgery and spine surgery.', 'Combines infrared optical cameras with software that merges preoperative imaging (CT/MRI) or intraoperative scans (O-arm) to the patient in the OR. The S8 platform features an intuitive touch-screen interface and supports over 200 tracked instruments for various procedures.', 'Available worldwide: as Medtronic''s 8th-generation navigation system, it''s FDA cleared, CE marked, and used in 1000+ surgical centers across North America, Europe, Asia, and Latin America.', true, NOW(), NOW()),

('d0000001-0001-0001-0001-000000000023', '11111111-1111-1111-1111-111111111111', 'OsteoCool RF Ablation System', 'OST-RFA-001', 'Ablation', 'Spine', 'Cooled radiofrequency ablation platform for palliative treatment of painful bone tumors, including spinal metastases.', 'Employs internally cooled RF probes to prevent overheating of surrounding tissue. The generator can power dual probes simultaneously (OsteoCool 1.0) or up to four probes at once (OsteoCool 2.0) for larger lesions. Ablation cycles typically last 6–15 minutes per lesion, heating tissue to ~90°C.', 'Cleared in the U.S. (FDA) for spinal tumor ablation and carries the CE mark in Europe. Used in interventional radiology and spine oncology practices across North America, Europe, and Asia-Pacific.', true, NOW(), NOW())

ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  technical_specifications = EXCLUDED.technical_specifications,
  global_availability = EXCLUDED.global_availability,
  updated_at = NOW();
